### ISSUE TITLE
與 DSM 7.0 不相容

### ISSUE THREAD

**Issue by gnehs** [gnehs/PokaPlayer#201]
PokaPlayer 與 DSM 7.0 不相容，若要繼續使用請勿更新至 DSM 7.0。

---
若時間許可，PokaPlayer 將會在近期釋出與 DSM 7.0 相容之更新。

**Comment by yuanqiuye** [comment]
想請問一下現在還是不兼容嗎QQ，DSM7.0現在還是取不到歌曲資料

**Comment by gnehs** [comment]
請問你的版本號是多少，我現在用 3.6.5 是可以正常存取到音樂資料的

**Comment by yuanqiuye** [comment]
Poka version: 3.6.5
DSM version: 7.1-42661
Debug message:
```
(node:19) UnhandledPromiseRejectionWarning: ReferenceError: x is not defined

2022-05-10T08:02:12.330168749Z,stdout,    at async /app/dataModule.js:58:5

2022-05-10T08:02:12.330137921Z,stdout,    at async Promise.all (index 2)

2022-05-10T08:02:12.330107091Z,stdout,    at async /app/dataModule.js:63:36

2022-05-10T08:02:12.330071079Z,stdout,    at async Object.getHome (/app/dataModule/dsm.js:191:23)

2022-05-10T08:02:12.330032648Z,stdout,    at processTicksAndRejections (internal/process/task_queues.js:95:5)

2022-05-10T08:02:12.329998461Z,stdout,    at runMicrotasks (<anonymous>)

2022-05-10T08:02:12.329945439Z,stdout,    at getAlbums (/app/dataModule/dsm.js:297:41)

TypeError: Cannot read property 'albums' of undefined


2022-05-10T08:01:38.327423771Z,stdout,    at processTicksAndRejections (internal/process/task_queues.js:95:5)

2022-05-10T08:01:38.327358630Z,stdout,    at runMicrotasks (<anonymous>)

2022-05-10T08:01:38.327296012Z,stdout,    at /app/dataModule.js:209:19

2022-05-10T08:01:38.326760709Z,stdout,(node:19) UnhandledPromiseRejectionWarning: ReferenceError: x is not defined

2022-05-10T08:01:35.102938808Z,stdout,    at async /app/dataModule.js:116:19

2022-05-10T08:01:35.102902192Z,stdout,    at processTicksAndRejections (internal/process/task_queues.js:95:5)

2022-05-10T08:01:35.102868689Z,stdout,    at runMicrotasks (<anonymous>)

2022-05-10T08:01:35.102813345Z,stdout,    at Object.getFolderFiles (/app/dataModule/dsm.js:351:40)

TypeError: Cannot read property 'items' of undefined

2022-05-10T08:01:29.373975951Z,stdout,    at async /app/dataModule.js:116:19

2022-05-10T08:01:29.373936387Z,stdout,    at processTicksAndRejections (internal/process/task_queues.js:95:5)

2022-05-10T08:01:29.373901412Z,stdout,    at runMicrotasks (<anonymous>)

2022-05-10T08:01:29.373845516Z,stdout,    at Object.getFolderFiles (/app/dataModule/dsm.js:351:40)

TypeError: Cannot read property 'items' of undefined

2022-05-10T08:01:20.314573728Z,stdout,"(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
"

"
2022-05-10T08:01:20.314291843Z,stdout,(Use `node --trace-warnings ...` to show where the warning was created)

2022-05-10T08:01:20.314243088Z,stdout,    at processTicksAndRejections (internal/process/task_queues.js:95:5)

2022-05-10T08:01:20.314204911Z,stdout,    at runMicrotasks (<anonymous>)

2022-05-10T08:01:20.314137678Z,stdout,    at /app/dataModule.js:209:19

2022-05-10T08:01:20.313550057Z,stdout,(node:19) UnhandledPromiseRejectionWarning: ReferenceError: x is not defined
```

**Comment by gnehs** [comment]
你現在音樂庫有專輯嗎

**Comment by yuanqiuye** [comment]
有的喔

**Comment by gnehs** [comment]
方便給我帳號密碼讓我連進去試試看嗎
https://t.me/gnehs_owo
